"""Generate license certificate PDFs."""
import io
from reportlab.lib.pagesizes import A4
from reportlab.lib.colors import HexColor
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas


def generate_license_pdf(license_data: dict, face_data: dict, buyer_data: dict) -> bytes:
    buf = io.BytesIO()
    c = canvas.Canvas(buf, pagesize=A4)
    w, h = A4

    gold = HexColor("#c9a96e")
    dark = HexColor("#0a0a0c")
    gray = HexColor("#666666")
    white = HexColor("#ffffff")

    # Background
    c.setFillColor(dark)
    c.rect(0, 0, w, h, fill=1)

    # Gold top accent bar
    c.setFillColor(gold)
    c.rect(0, h - 8*mm, w, 8*mm, fill=1)

    # Logo
    c.setFillColor(white)
    c.setFont("Helvetica-Bold", 28)
    c.drawString(30*mm, h - 30*mm, "face")
    c.setFillColor(gold)
    c.drawString(30*mm + c.stringWidth("face", "Helvetica-Bold", 28), h - 30*mm, "pay")

    # Title
    c.setFillColor(gold)
    c.setFont("Helvetica", 11)
    c.drawString(30*mm, h - 42*mm, "LICENSE CERTIFICATE")

    c.setFillColor(white)
    c.setFont("Helvetica-Bold", 22)
    c.drawString(30*mm, h - 55*mm, "Face License Agreement")

    # Divider
    c.setStrokeColor(HexColor("#333333"))
    c.setLineWidth(0.5)
    c.line(30*mm, h - 62*mm, w - 30*mm, h - 62*mm)

    # License details
    y = h - 80*mm
    details = [
        ("License ID", license_data.get("id", "N/A")[:18] + "..."),
        ("Face Name", face_data.get("name", "N/A")),
        ("License Type", license_data.get("license_type", "standard").title()),
        ("Usage Purpose", license_data.get("usage_purpose", "N/A")),
        ("Duration", f"{license_data.get('duration_months', 0)} months"),
        ("Price Paid", f"${license_data.get('price_paid', 0):.2f}"),
        ("Status", license_data.get("status", "active").upper()),
        ("Buyer", buyer_data.get("name", "N/A")),
        ("Buyer Email", buyer_data.get("email", "N/A")),
        ("Issued", license_data.get("created_at", "N/A")[:10]),
        ("Expires", license_data.get("expires_at", "N/A")[:10]),
    ]

    for label, value in details:
        c.setFillColor(gray)
        c.setFont("Helvetica", 10)
        c.drawString(30*mm, y, label)
        c.setFillColor(white)
        c.setFont("Helvetica-Bold", 11)
        c.drawString(80*mm, y, str(value))
        y -= 10*mm

    # Terms section
    y -= 10*mm
    c.setStrokeColor(HexColor("#333333"))
    c.line(30*mm, y + 5*mm, w - 30*mm, y + 5*mm)

    y -= 5*mm
    c.setFillColor(gold)
    c.setFont("Helvetica-Bold", 11)
    c.drawString(30*mm, y, "Terms & Conditions")

    y -= 12*mm
    c.setFillColor(gray)
    c.setFont("Helvetica", 8)
    terms = [
        "1. This license grants the buyer rights to use the licensed face as specified above.",
        "2. Usage beyond the specified purpose requires an additional license.",
        "3. The license is non-transferable and bound to the buyer listed above.",
        "4. The provider retains all intellectual property rights to their likeness.",
        "5. Misuse of this license may result in revocation and legal action.",
        "6. This certificate is digitally generated and verified by FacePay.",
    ]
    for line in terms:
        c.drawString(30*mm, y, line)
        y -= 6*mm

    # Footer
    c.setFillColor(HexColor("#444444"))
    c.setFont("Helvetica", 8)
    c.drawString(30*mm, 15*mm, "Generated by FacePay — AI Face Licensing Marketplace")
    c.drawRightString(w - 30*mm, 15*mm, "facepay-sigma.vercel.app")

    # Gold bottom bar
    c.setFillColor(gold)
    c.rect(0, 0, w, 3*mm, fill=1)

    c.save()
    buf.seek(0)
    return buf.read()
